title: A beginner.
description: >-
  اريد تعليم السوس ميديا موقع التواصل الاجتماعي انستقرام سناب شات ملاحظه يوحد
  ضعف لغه لانجليش هل يوجد بث مباشر تعلين I want to teach the social media site
  Instagram Snapchat a note that unites the weakness of langlich language is
  there a live broadcast  
template:
  repo: a-beginner.-template
  name: a-beginner.
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
